name: appfront
description: A new Flutter project.
publish_to: "none"
version: 0.1.7

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.5
  http: ^1.2.1
  desktop_window: ^0.4.0
  intl: ^0.19.0
  geolocator: ^11.0.0
  flutter_riverpod: ^2.5.1
  qr_code_scanner: ^1.0.1
  riverpod: ^2.5.1
  carousel_slider:
  flutter_naver_map: ^1.2.2+flutter3.22
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  cookie_jar: ^4.0.8

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/fonts/
    - lib/Screen/Auth/Login/widgets/img/
  fonts:
    - family: BMJUA
      fonts:
        - asset: lib/assets/fonts/BMJUA.ttf
    - family: Maple
      fonts:
        - asset: lib/assets/fonts/Maplestory Bold.ttf
